#!/usr/bin/env sh
# package name as arg
#
# builds a package or fetches it from local cache
# if that fails, tries using cache.nixos.org
u="$(dirname "$0")"

$u/try-or-substitute "nix-shell -p $@ --run true" || exit
