#!/usr/bin/env sh
# no args
# sets up caching to attic, should be the first thing run by all scripts
if [ -f .no-cache ]; then exit 0; fi

u="$(dirname "$0")"

# use only attic cache, enable flakes
mkdir -p ~/.config/nix
echo -e "
experimental-features = nix-command flakes\n
substituters = http://attic.app-attic.svc/main\n
trusted-public-keys = main:1jU1/ydAUG+eKm24k9MMGP13Bv+MmgxPyf169DNHZRM=
" > ~/.config/nix/nix.conf

# login to cache
$u/build-or-fetch attic-client || exit
nix-shell -p attic-client --run "attic login az http://attic.app-attic.svc $ATTIC_TOKEN" || exit
