#!/usr/bin/env sh
# no args
# sets up caching to attic, should be the first thing run by all scripts
if [ -f .no-cache ]; then exit 0; fi

u="$(dirname "$0")"

# use only attic cache, enable flakes & keep-going
$u/setup-nix-conf
echo "
substituters = http://attic.app-attic.svc/main
trusted-public-keys = main:1jU1/ydAUG+eKm24k9MMGP13Bv+MmgxPyf169DNHZRM=
" >> ~/.config/nix/nix.conf

$u/append-nix-conf

# login to cache
$u/build-or-fetch attic-client || exit
nix-shell -p attic-client --run "attic login az http://attic.app-attic.svc $ATTIC_TOKEN" || exit
