#!/usr/bin/env sh
#
# runs nix flake check --all-systems

u="$(dirname "$0")/utils"
$u/cache-setup || exit
$u/cache-continuously & sleep 5

# replace ./sops with a dummy dir if it exists, nix complains it can't access it even though it's not needed
$u/build-or-fetch git || exit
nix-shell -p git --run "test -d sops && git rm sops && mkdir sops && touch sops/.gitkeep && git add -A"

# attempt builds without using cache.nixos.org, if that fails use default substituters
systems=$(nix eval .\#nixosConfigurations --apply 'v: builtins.toJSON (builtins.attrNames v)') || exit

$u/build-or-fetch jq || exit
for system in $(echo $systems | nix-shell -p jq --run "jq -r 'fromjson | .[]'")
do
	$u/try-or-substitute "nix build --no-link .#nixosConfigurations.$system.config.system.build.toplevel" || exit
done

$u/cache-all
